
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Using common LTS versions of Node.js

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Enable caching for npm dependencies to speed up builds

    - name: Install dependencies
      run: npm ci # 'npm ci' is generally recommended for CI for faster, more reliable builds

    - name: Lint project
      # This step assumes you have a lint script defined in your package.json, e.g., "lint": "eslint ."
      # If not, you might need to adjust this command or add a lint script.
      run: npm run lint

    - name: Build project
      # This step assumes you have a build script defined in your package.json, e.g., "build": "vite build"
      run: npm run build

    # If you have tests, you can add a step like this:
    # - name: Run tests
    #   run: npm test
